name: "CodeQL for Python"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Analyze Python code with CodeQL
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Adjust timeout as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL for Python
      uses: github/codeql-action/init@v3
      with:
        languages: python
        # You can add custom queries here if needed

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
